import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Step 0: Load environment variables
load_dotenv()
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise ValueError("GOOGLE_API_KEY not found in .env")
else:
    print(" Token loaded\n")


# LLM
def load_llm(temperature=0.4):
    return ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        temperature=temperature,
        max_output_tokens=2048,
        google_api_key=GOOGLE_API_KEY
    )


# PART 1 — PROFESSIONAL SUMMARY GENERATOR

SUMMARY_PROMPT_TEMPLATE = """
You are an elite professional summary and profile writer with expertise in human-centered communication, executive branding, storytelling, professional positioning, and personalized content generation.

Your responsibility is to generate a highly polished, realistic, engaging, and deeply personalized professional summary that feels genuinely written by a human rather than generated by an AI system.

The generated summary must sound natural, emotionally intelligent, context-aware, and professionally authentic while maintaining clarity, structure, and readability.

PERSON DETAILS:
Name: {full_name}
Job Title: {job_title}
Bio: {bio}

SUMMARY DETAILS:
Tone: {tone}
Summary Length: {summary_length}

WRITING OBJECTIVES:

- Create a professional summary that feels authentic, human-written, and naturally expressive.
- The writing should reflect realistic human communication patterns instead of robotic or overly formal AI-generated language.
- Build a strong professional identity around the provided details while preserving natural flow and readability.
- Make the summary immersive, thoughtful, and personalized rather than generic or template-like.
- Highlight the individual's technical expertise, professional interests, learning mindset, adaptability, communication abilities, and career aspirations naturally within the writing.
- Expand meaningfully on the provided bio with contextual elaboration, professional depth, and realistic career-oriented interpretation.
- Include subtle storytelling elements where appropriate to make the content feel more organic and engaging.
- Ensure the writing captures professional confidence without sounding exaggerated or artificial.
- Emphasize qualities such as curiosity, growth mindset, collaboration, problem-solving ability, consistency, dedication, and technical passion whenever relevant.
- Maintain a strong balance between professionalism and human warmth.
- The summary should feel suitable for platforms such as LinkedIn, portfolios, resumes, professional introductions, internship profiles, startup applications, networking profiles, or AI/tech industry presentations.

LANGUAGE & WRITING STYLE GUIDELINES:

- Write in a polished, sophisticated, and naturally flowing human tone.
- Avoid repetitive sentence structures.
- Avoid robotic phrasing or AI-like generic wording.
- Avoid excessive buzzwords unless contextually meaningful.
- Ensure smooth transitions between ideas and paragraphs.
- Use varied sentence lengths and natural conversational rhythm.
- Make the content emotionally intelligent while remaining professional.
- Use strong but realistic vocabulary appropriate for professional communication.
- Keep the tone fully consistent throughout the summary.
- Make the content descriptive, insightful, and detailed without sounding unnecessarily verbose.
- Focus heavily on readability, authenticity, and professional credibility.
- If the tone is formal, maintain polished business-level language.
- If the tone is friendly or conversational, introduce a warmer and more approachable writing style while preserving professionalism.
- If the summary length is long, generate a detailed multi-paragraph professional narrative with rich elaboration and contextual insights.

CONTENT ENHANCEMENT REQUIREMENTS:

- Infer and naturally expand upon the person's likely strengths, ambitions, and working style based on the provided information.
- Add meaningful professional depth while staying aligned with the original details.
- Highlight technical skills, industry interests, project exposure, tools, technologies, and learning attitude whenever relevant.
- Create a sense of credibility, competence, and authenticity.
- Ensure the summary sounds believable and professionally realistic.
- Make the writing feel personalized to the individual instead of universally applicable.

OUTPUT REQUIREMENTS:

- Generate only the final professional summary.
- Do not include headings, labels, explanations, bullet points, or notes.
- The final response must be presentation-ready.
- The output must feel naturally written by a real person with professional writing expertise.
- Prioritize authenticity and human-like expression over generic AI-generated structure.

Now generate the detailed professional summary.
"""

def build_summary_chain():
    llm = load_llm(temperature=0.3)
    prompt = PromptTemplate(
        input_variables=["full_name", "job_title", "bio", "tone", "summary_length"],
        template=SUMMARY_PROMPT_TEMPLATE
    )
    return prompt | llm | StrOutputParser()


def generate_summary(person_details: dict) -> str:
    print("\n SUMMARY CONFIGURATION")
    print("   Tone options: formal | friendly | conversational | inspirational | confident\n")

    tone          = input("   Tone                              : ").strip() or "professional"
    summary_length = input("   Summary Length (short/medium/long): ").strip() or "medium"

    chain = build_summary_chain()

    final_input = {
        **person_details,
        "tone": tone,
        "summary_length": summary_length,
    }

    print("\n Generating professional summary...\n")
    summary = chain.invoke(final_input)

    print(" GENERATED PROFESSIONAL SUMMARY")
    print(summary)

    return summary


# PART 2 — EMAIL GENERATOR

EMAIL_PROMPT_TEMPLATE = """
You are an elite professional email writer and communication strategist with expertise in corporate communication, networking emails, business outreach, client handling, follow-ups, HR communication, and executive correspondence.

Your task is to generate a highly personalized, professional, and natural-sounding email based on the sender's personality, communication style, and the provided email request details.

SENDER PROFILE (PERSON CONTEXT)
The following information describes the sender's personality, communication habits, profession, behavior, communication style, values, expertise, and professional background.

Use this information carefully to shape:
- writing style
- sentence structure
- tone
- vocabulary
- confidence level
- professionalism
- warmth
- empathy
- assertiveness
- persuasion level
- technical depth
- conversational style

SENDER DETAILS:
{person_context}

EMAIL REQUEST DETAILS

Recipient Name:
{recipient_name}

Recipient Role / Position:
{recipient_role}

Email Purpose:
{email_purpose}

Desired Tone:
{tone}

Key Points That Must Be Included:
{key_points}

EMAIL WRITING INSTRUCTIONS

1. PERSONALIZATION
- Make the email feel genuinely written by a real human.
- Adapt the language and writing style according to the sender's personality and professional background.
- Use subtle personalization where appropriate.
- Avoid robotic or template-like phrasing.

2. TONE MATCHING
Strictly follow the requested tone:
- Professional
- Friendly
- Assertive
- Empathetic
- Formal
- Persuasive
- Confident
- Diplomatic
- Casual Professional
- Apologetic
- Appreciative
- Motivational

Blend tones naturally if multiple tones are provided.

3. EMAIL STRUCTURE
The email MUST include:
- Subject Line
- Professional Greeting
- Opening Paragraph
- Main Body
- Clear Call-To-Action
- Professional Closing
- Signature with sender name and designation

4. WRITING QUALITY
- Keep the flow smooth and coherent.
- Ensure clarity and readability.
- Avoid unnecessary repetition.
- Use concise but meaningful language.
- Maintain professionalism throughout.
- Make transitions between paragraphs natural.

5. CONTEXTUAL INTELLIGENCE
- Infer missing details intelligently when needed.
- If the purpose is business-related, maintain corporate professionalism.
- If the email is networking-oriented, make it warm and relationship-focused.
- If it is a complaint or escalation, make it firm but respectful.
- If it is a follow-up, ensure continuity and politeness.
- If it is sales or outreach, make it persuasive without sounding aggressive.

6. NATURAL HUMAN STYLE
- Avoid AI-like wording.
- Do NOT overuse buzzwords.
- Use realistic corporate communication language.
- Ensure the email sounds authentic and believable.

7. OUTPUT FORMAT
Generate ONLY the final email in the following format:

Subject: <subject line>

Dear/Hello <recipient name>,

<complete email body>

Best regards,
<sender name>
<sender job title>

SPECIAL INSTRUCTIONS


- If important information is missing, make reasonable professional assumptions.
- If the sender's personality suggests a unique communication style, reflect it naturally.
- Prioritize professionalism, clarity, and authenticity.
- Ensure the final email is polished and ready to send without further editing.
- Do not explain the email.
- Do not include placeholders in the final response.
- Do not mention AI or prompt instructions.
- Make the email emotionally intelligent where appropriate.

Generate the complete email now.
"""

def build_email_chain(person_context_str: str):
    llm = load_llm(temperature=0.3)
    prompt = PromptTemplate(
        template=EMAIL_PROMPT_TEMPLATE,
        input_variables=[
            "person_context",
            "recipient_name",
            "recipient_role",
            "email_purpose",
            "tone",
            "key_points",
        ]
    )

    chain = (
        {
            "person_context": RunnablePassthrough() | (lambda _: person_context_str),
            "recipient_name": RunnablePassthrough() | (lambda x: x["recipient_name"]),
            "recipient_role": RunnablePassthrough() | (lambda x: x["recipient_role"]),
            "email_purpose":  RunnablePassthrough() | (lambda x: x["email_purpose"]),
            "tone":           RunnablePassthrough() | (lambda x: x["tone"]),
            "key_points":     RunnablePassthrough() | (lambda x: x["key_points"]),
        }
        | prompt
        | llm
        | StrOutputParser()
    )
    return chain


def get_email_details() -> dict:
    print("\n ENTER EMAIL DETAILS")
    print("   Tone options: formal | friendly | assertive | empathetic | persuasive\n")

    return {
        "recipient_name": input("   Recipient Name   : ").strip(),
        "recipient_role": input("   Recipient Role   : ").strip(),
        "email_purpose":  input("   Email Purpose    : ").strip(),
        "tone":           input("   Tone             : ").strip() or "formal",
        "key_points":     input("   Key Points       : ").strip(),
    }


def run_email_generator(person_context_str: str):
    chain = build_email_chain(person_context_str)
    print("\n Email Generator Ready! Type 'exit' to quit.\n")

    while True:
        choice = input("Generate a new email? (yes/exit): ").strip().lower()

        if choice in ["exit", "quit", "no"]:
            print("\n Goodbye!")
            break

        if choice != "yes":
            print("   Please type 'yes' or 'exit'.")
            continue

        email_details = get_email_details()

        print("\n Generating email...\n")
        result = chain.invoke(email_details)


        print(" GENERATED EMAIL")
        print(result)


# MAIN — Combined Flow

if __name__ == "__main__":

    # ── Step 1: Collect sender / person details ──────────────
    print("        PROFESSIONAL SUMMARY + EMAIL GENERATOR")
    print("\n ENTER SENDER DETAILS\n")

    person_details = {
        "full_name":           input("   Full Name            : ").strip(),
        "job_title":           input("   Job Title            : ").strip(),
        "bio":                 input("   Bio                  : ").strip(),
        "communication_style": input("   Communication Style  : ").strip(),
        "personality":         input("   Personality Traits   : ").strip(),
    }

    # Remove blank fields
    person_details = {k: v for k, v in person_details.items() if v}

    if not person_details:
        print("\n  No details entered. Continuing without person context.")

    print("\n Person details saved!")

    # ── Step 2: Generate professional summary ────────────────
    print("          STEP 1 OF 2 — PROFESSIONAL SUMMARY")

    generated_summary = generate_summary(person_details)

    # ── Step 3: Build enriched person context string ─────────
    # Merge raw person fields with the generated summary so the
    # email chain benefits from the full, richly written profile.
    person_context_parts = [
        f"{k.replace('_', ' ').title()}: {v}"
        for k, v in person_details.items()
    ]
    person_context_parts.append(f"\nProfessional Summary:\n{generated_summary}")
    person_context_str = "\n".join(person_context_parts)

    # ── Step 4: Run email generator ──────────────────────────
    print("          STEP 2 OF 2 — EMAIL GENERATOR")

    run_email_generator(person_context_str)