import os
import json
import datetime
import streamlit as st
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Page config 
st.set_page_config(
    page_title="ProWriter AI",
    page_icon="✍️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Styling
st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@700&display=swap');

  html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

  /* Sidebar */
  [data-testid="stSidebar"] {
    background: linear-gradient(160deg, #0f172a 0%, #1e293b 100%);
    color: #e2e8f0;
  }
  [data-testid="stSidebar"] h1, [data-testid="stSidebar"] h2,
  [data-testid="stSidebar"] h3, [data-testid="stSidebar"] label,
  [data-testid="stSidebar"] p { color: #e2e8f0 !important; }
  [data-testid="stSidebar"] .stSelectbox > div > div { background: #1e293b; color: #e2e8f0; }

  /* Hero banner */
  .hero-banner {
    background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #0f172a 100%);
    border-radius: 16px;
    padding: 2.5rem 2rem;
    margin-bottom: 1.5rem;
    text-align: center;
    border: 1px solid #334155;
  }
  .hero-banner h1 {
    font-family: 'Playfair Display', serif;
    font-size: 2.4rem;
    color: #f8fafc;
    margin: 0 0 0.4rem 0;
  }
  .hero-banner p { color: #94a3b8; font-size: 1rem; margin: 0; }

  /* Cards */
  .card {
    background: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 1.6rem 1.8rem;
    margin-bottom: 1.2rem;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
  }
  .card-header {
    font-size: 0.72rem;
    font-weight: 700;
    letter-spacing: .12em;
    text-transform: uppercase;
    color: #64748b;
    margin-bottom: 1rem;
  }

  /* Output boxes */
  .output-box {
    background: #f8fafc;
    border: 1px solid #cbd5e1;
    border-left: 4px solid #3b82f6;
    border-radius: 8px;
    padding: 1.4rem 1.6rem;
    white-space: pre-wrap;
    font-size: 0.93rem;
    line-height: 1.75;
    color: #1e293b;
    margin-top: 0.8rem;
  }
  .email-box {
    border-left-color: #8b5cf6;
    font-family: 'Inter', sans-serif;
  }

  /* Step badges */
  .step-badge {
    display: inline-block;
    background: #dbeafe;
    color: #1d4ed8;
    font-size: 0.72rem;
    font-weight: 700;
    padding: 3px 10px;
    border-radius: 999px;
    letter-spacing: .08em;
    margin-bottom: 0.6rem;
    text-transform: uppercase;
  }

  /* Showcase table */
  .showcase-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.6rem 0;
    border-bottom: 1px solid #f1f5f9;
    font-size: 0.9rem;
  }
  .showcase-row:last-child { border-bottom: none; }
  .tag {
    background: #f0fdf4;
    color: #166534;
    font-size: 0.72rem;
    padding: 2px 8px;
    border-radius: 999px;
    font-weight: 600;
  }

  /* Primary button override */
  .stButton > button[kind="primary"] {
    background: linear-gradient(135deg, #2563eb, #4f46e5);
    color: white;
    border: none;
    border-radius: 8px;
    font-weight: 600;
    padding: 0.5rem 1.4rem;
    transition: opacity .2s;
  }
  .stButton > button[kind="primary"]:hover { opacity: 0.88; }
</style>
""", unsafe_allow_html=True)

# Helpers
SHOWCASE_FILE = "showcase_log.json"

def load_showcase() -> list:
    if os.path.exists(SHOWCASE_FILE):
        with open(SHOWCASE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []

def save_to_showcase(record: dict):
    log = load_showcase()
    log.append(record)
    with open(SHOWCASE_FILE, "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2, ensure_ascii=False)

def load_llm(temperature=0.5):
    return ChatOllama(model="llama3.2", temperature=temperature)

# Prompts
SUMMARY_PROMPT_TEMPLATE = """
You are an elite professional summary and profile writer with expertise in human-centered communication, executive branding, storytelling, professional positioning, and personalized content generation.

Your responsibility is to generate a highly polished, realistic, engaging, and deeply personalized professional summary that feels genuinely written by a human rather than generated by an AI system.

PERSON DETAILS:
Name: {full_name}
Job Title: {job_title}
Bio: {bio}

SUMMARY DETAILS:
Tone: {tone}
Summary Length: {summary_length}

WRITING OBJECTIVES:
- Create a professional summary that feels authentic, human-written, and naturally expressive.
- Build a strong professional identity around the provided details while preserving natural flow and readability.
- Make the summary immersive, thoughtful, and personalized rather than generic or template-like.
- Highlight the individual's technical expertise, professional interests, learning mindset, adaptability, communication abilities, and career aspirations naturally within the writing.
- Expand meaningfully on the provided bio with contextual elaboration, professional depth, and realistic career-oriented interpretation.
- Ensure the writing captures professional confidence without sounding exaggerated or artificial.

LANGUAGE & WRITING STYLE GUIDELINES:
- Write in a polished, sophisticated, and naturally flowing human tone.
- Avoid repetitive sentence structures and robotic phrasing.
- Use varied sentence lengths and natural conversational rhythm.
- Make the content emotionally intelligent while remaining professional.
- Keep the tone fully consistent throughout the summary.
- If the tone is formal, maintain polished business-level language.
- If the tone is friendly or conversational, introduce a warmer and more approachable writing style.

OUTPUT REQUIREMENTS:
- Generate only the final professional summary.
- Do not include headings, labels, explanations, bullet points, or notes.
- The final response must be presentation-ready.
- Prioritize authenticity and human-like expression over generic AI-generated structure.

Now generate the detailed professional summary.
"""

EMAIL_PROMPT_TEMPLATE = """
You are an elite professional email writer and communication strategist.

SENDER PROFILE:
{person_context}

EMAIL REQUEST DETAILS:
Recipient Name: {recipient_name}
Recipient Role: {recipient_role}
Email Purpose: {email_purpose}
Desired Tone: {tone}
Key Points to Include: {key_points}

EMAIL WRITING INSTRUCTIONS:
1. Make the email feel genuinely written by a real human.
2. Adapt the writing style according to the sender's personality and professional background.
3. Strictly follow the requested tone.
4. The email MUST include: Subject Line, Professional Greeting, Opening Paragraph, Main Body, Clear Call-To-Action, Professional Closing, Signature.
5. Keep the flow smooth, concise, and professional.
6. Avoid AI-like wording and overused buzzwords.

OUTPUT FORMAT:
Subject: <subject line>

Dear/Hello <recipient name>,

<complete email body>

Best regards,
<sender name>
<sender job title>

Generate the complete email now.
"""

def build_summary_chain():
    llm = load_llm(temperature=0.3)
    prompt = PromptTemplate(
        input_variables=["full_name", "job_title", "bio", "tone", "summary_length"],
        template=SUMMARY_PROMPT_TEMPLATE,
    )
    return prompt | llm | StrOutputParser()

def build_person_context(person_details: dict, generated_summary: str) -> str:
    original_block = "\n".join(
        f"{k.replace('_', ' ').title()}: {v}"
        for k, v in person_details.items()
        if k not in ("full_name",)
    )
    summary_block = f"\n── AI-Generated Professional Summary ──\n{generated_summary}\n"
    return f"{original_block}\n{summary_block}"

def build_email_chain(person_context_str: str):
    llm = load_llm(temperature=0.5)
    prompt = PromptTemplate(
        template=EMAIL_PROMPT_TEMPLATE,
        input_variables=["person_context", "recipient_name", "recipient_role",
                         "email_purpose", "tone", "key_points"],
    )
    chain = (
        {
            "person_context": RunnablePassthrough() | (lambda _: person_context_str),
            "recipient_name": RunnablePassthrough() | (lambda x: x["recipient_name"]),
            "recipient_role": RunnablePassthrough() | (lambda x: x["recipient_role"]),
            "email_purpose":  RunnablePassthrough() | (lambda x: x["email_purpose"]),
            "tone":           RunnablePassthrough() | (lambda x: x["tone"]),
            "key_points":     RunnablePassthrough() | (lambda x: x["key_points"]),
        }
        | prompt | llm | StrOutputParser()
    )
    return chain

# Session state init
for key, default in {
    "step": 1,
    "person_details": {},
    "generated_summary": "",
    "person_context_str": "",
    "emails": [],
    "summary_tone": "professional",
    "summary_length": "medium",
}.items():
    if key not in st.session_state:
        st.session_state[key] = default

# Sidebar
with st.sidebar:
    st.markdown("## ✍️ ProWriter AI")
    st.markdown("---")

    # Navigation
    st.markdown("### Navigation")
    steps = {
        1: "📋 Sender Details",
        2: "📝 Professional Summary",
        3: "📧 Email Generator",
        4: "📊 Showcase Log",
    }
    for num, label in steps.items():
        is_active = st.session_state.step == num
        btn_type = "primary" if is_active else "secondary"
        if st.button(label, key=f"nav_{num}", use_container_width=True, type=btn_type):
            st.session_state.step = num
            st.rerun()

    st.markdown("---")

    # Quick stats
    log = load_showcase()
    st.markdown("### Session Stats")
    col1, col2 = st.columns(2)
    col1.metric("Customers", len(log))
    col2.metric("Emails", sum(e.get("emails_generated", 0) for e in log))

    st.markdown("---")
    st.caption("Powered by LLaMA 3.2 via Ollama")

# Hero
st.markdown("""
<div class="hero-banner">
  <h1>Professional Summary & Email Generator</h1>
  <p>Generate human-like professional summaries and polished emails — powered by local LLM</p>
</div>
""", unsafe_allow_html=True)

# STEP 1 — Sender Details
if st.session_state.step == 1:
    st.markdown('<div class="step-badge">Step 1 of 3</div>', unsafe_allow_html=True)
    st.subheader("Sender Details")
    st.caption("Tell us about the person whose summary and emails we'll be generating.")

    with st.form("sender_form"):
        col1, col2 = st.columns(2)
        with col1:
            full_name = st.text_input("Full Name *", placeholder="e.g. Riya Shah")
            job_title = st.text_input("Job Title *", placeholder="e.g. ML Engineer")
        with col2:
            communication_style = st.text_input("Communication Style", placeholder="e.g. clear, concise, analytical")
            personality = st.text_input("Personality Traits", placeholder="e.g. curious, collaborative, detail-oriented")

        bio = st.text_area(
            "Bio *",
            placeholder="Brief professional background — skills, projects, goals, experience...",
            height=130,
        )

        submitted = st.form_submit_button("Save & Continue →", type="primary", use_container_width=True)

    if submitted:
        if not full_name or not job_title or not bio:
            st.error("Please fill in Name, Job Title, and Bio to continue.")
        else:
            st.session_state.person_details = {
                k: v for k, v in {
                    "full_name": full_name,
                    "job_title": job_title,
                    "bio": bio,
                    "communication_style": communication_style,
                    "personality": personality,
                }.items() if v
            }
            st.session_state.step = 2
            st.rerun()

# STEP 2 — Professional Summary

elif st.session_state.step == 2:
    st.markdown('<div class="step-badge">Step 2 of 3</div>', unsafe_allow_html=True)
    st.subheader("Professional Summary")

    details = st.session_state.person_details

    # Person info card
    with st.expander("👤 Sender Details", expanded=False):
        cols = st.columns(2)
        for i, (k, v) in enumerate(details.items()):
            cols[i % 2].markdown(f"**{k.replace('_', ' ').title()}:** {v}")

    st.markdown("---")
    st.markdown("#### Summary Configuration")

    col1, col2 = st.columns(2)
    with col1:
        tone = st.selectbox(
            "Tone",
            ["professional", "formal", "friendly", "conversational", "inspirational", "confident"],
            index=0,
        )
    with col2:
        length = st.selectbox("Summary Length", ["short", "medium", "long"], index=1)

    if st.button("✨ Generate Summary", type="primary", use_container_width=True):
        with st.spinner("Crafting your professional summary..."):
            chain = build_summary_chain()
            summary = chain.invoke({**details, "tone": tone, "summary_length": length})
            st.session_state.generated_summary = summary
            st.session_state.summary_tone = tone
            st.session_state.summary_length = length
            st.session_state.person_context_str = build_person_context(details, summary)

    if st.session_state.generated_summary:
        st.markdown("#### Generated Summary")
        st.markdown(
            f'<div class="output-box">{st.session_state.generated_summary}</div>',
            unsafe_allow_html=True,
        )

        col1, col2 = st.columns(2)
        with col1:
            st.download_button(
                "⬇ Download Summary",
                data=st.session_state.generated_summary,
                file_name=f"summary_{details.get('full_name','user').replace(' ','_')}.txt",
                mime="text/plain",
                use_container_width=True,
            )
        with col2:
            if st.button("Continue to Email Generator →", type="primary", use_container_width=True):
                st.session_state.step = 3
                st.rerun()

# STEP 3 — Email Generator

elif st.session_state.step == 3:
    st.markdown('<div class="step-badge">Step 3 of 3</div>', unsafe_allow_html=True)
    st.subheader("Email Generator")

    if not st.session_state.person_context_str:
        st.warning("Please complete Step 1 & 2 first before generating emails.")
        if st.button("← Back to Start"):
            st.session_state.step = 1
            st.rerun()
    else:
        st.caption(f"Generating emails for **{st.session_state.person_details.get('full_name','—')}** · {st.session_state.person_details.get('job_title','—')}")

        with st.expander("📄 View Sender Context (what the email model sees)", expanded=False):
            st.code(st.session_state.person_context_str, language=None)

        st.markdown("---")
        st.markdown("#### Email Details")

        with st.form("email_form"):
            col1, col2 = st.columns(2)
            with col1:
                recipient_name = st.text_input("Recipient Name *", placeholder="e.g. Dr. Priya Mehta")
                recipient_role = st.text_input("Recipient Role *", placeholder="e.g. Hiring Manager at Google")
            with col2:
                tone = st.selectbox(
                    "Email Tone",
                    ["formal", "friendly", "assertive", "empathetic", "persuasive",
                     "confident", "diplomatic", "appreciative", "apologetic"],
                )
                email_purpose = st.text_input("Email Purpose *", placeholder="e.g. Follow-up after interview")

            key_points = st.text_area(
                "Key Points to Include",
                placeholder="List the main points you want to cover, separated by commas or new lines...",
                height=100,
            )

            generate = st.form_submit_button("📧 Generate Email", type="primary", use_container_width=True)

        if generate:
            if not recipient_name or not recipient_role or not email_purpose:
                st.error("Please fill in Recipient Name, Role, and Email Purpose.")
            else:
                with st.spinner("Writing your email..."):
                    chain = build_email_chain(st.session_state.person_context_str)
                    email_text = chain.invoke({
                        "recipient_name": recipient_name,
                        "recipient_role": recipient_role,
                        "email_purpose":  email_purpose,
                        "tone":           tone,
                        "key_points":     key_points,
                    })
                    st.session_state.emails.append({
                        "recipient": recipient_name,
                        "purpose":   email_purpose,
                        "tone":      tone,
                        "body":      email_text,
                        "timestamp": datetime.datetime.now().strftime("%H:%M"),
                    })

        # Display all emails generated in this session
        if st.session_state.emails:
            st.markdown(f"#### Generated Emails ({len(st.session_state.emails)} this session)")

            for i, email in enumerate(reversed(st.session_state.emails), 1):
                with st.expander(
                    f"📧 Email #{len(st.session_state.emails) - i + 1}  ·  To: {email['recipient']}  ·  {email['purpose'][:40]}…  [{email['timestamp']}]",
                    expanded=(i == 1),
                ):
                    st.markdown(
                        f'<div class="output-box email-box">{email["body"]}</div>',
                        unsafe_allow_html=True,
                    )
                    st.download_button(
                        f"⬇ Download Email #{len(st.session_state.emails) - i + 1}",
                        data=email["body"],
                        file_name=f"email_to_{email['recipient'].replace(' ','_')}.txt",
                        mime="text/plain",
                        key=f"dl_email_{i}",
                    )

            # Save to showcase when user clicks done
            st.markdown("---")
            if st.button("✅ Save Session & View Showcase", type="primary", use_container_width=True):
                details = st.session_state.person_details
                record = {
                    "timestamp":        datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
                    "sender_name":      details.get("full_name", "Unknown"),
                    "sender_role":      details.get("job_title", "Unknown"),
                    "summary_tone":     st.session_state.summary_tone,
                    "summary_length":   st.session_state.summary_length,
                    "emails_generated": len(st.session_state.emails),
                    "summary_snippet":  st.session_state.generated_summary[:120].replace("\n", " ") + "…",
                }
                save_to_showcase(record)
                st.success("Session saved!")
                st.session_state.step = 4
                st.rerun()

# STEP 4 — Showcase Log

elif st.session_state.step == 4:
    st.subheader("📊 Showcase Log")
    st.caption("All past sessions saved on this machine.")

    log = load_showcase()

    if not log:
        st.info("No sessions saved yet. Complete a session to see it here.")
    else:
        total_emails = sum(e.get("emails_generated", 0) for e in log)
        c1, c2, c3 = st.columns(3)
        c1.metric("Total Sessions", len(log))
        c2.metric("Total Emails Generated", total_emails)
        c3.metric("Avg Emails / Session", f"{total_emails / len(log):.1f}")

        st.markdown("---")

        for i, entry in enumerate(reversed(log), 1):
            with st.expander(
                f"#{i}  {entry.get('sender_name','—')} · {entry.get('sender_role','—')}  [{entry.get('timestamp','—')}]"
            ):
                col1, col2 = st.columns(2)
                with col1:
                    st.markdown(f"**Summary Tone:** {entry.get('summary_tone','—')}")
                    st.markdown(f"**Summary Length:** {entry.get('summary_length','—')}")
                with col2:
                    st.markdown(f"**Emails Generated:** {entry.get('emails_generated', 0)}")
                    st.markdown(f"**Date:** {entry.get('timestamp','—')}")
                st.markdown(f"**Summary Snippet:** _{entry.get('summary_snippet','—')}_")

    if st.button("＋ Start New Session", type="primary"):
        for key in ["person_details", "generated_summary", "person_context_str", "emails"]:
            st.session_state[key] = {} if key == "person_details" else ([] if key == "emails" else "")
        st.session_state.step = 1
        st.rerun()