import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Load API Key
load_dotenv()

api_key = os.getenv("GOOGLE_API_KEY")

if not api_key:
    print(" GOOGLE_API_KEY not found!")
    exit()

print(" Token loaded successfully!\n")

# PERSON DETAILS

def get_person_details():
    print("ENTER PERSON DETAILS")

    full_name = input("Full Name        : ")
    job_title = input("Job Title        : ")
    bio = input("Bio              : ")


    return {
        "full_name": full_name,
        "job_title": job_title,
        "bio": bio,
    }


# SUMMARY DETAILS

def get_summary_details():
    print("ENTER SUMMARY DETAILS")

    tone = input("Tone              : ")
    summary_length = input("Summary Length (short/medium/long): ")

    return {
        "tone": tone,
        "summary_length": summary_length
    }


# LLM SETUP

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.3
    
)

# PROMPT TEMPLATE
template = """
You are an elite professional summary and profile writer with expertise in human-centered communication, executive branding, storytelling, professional positioning, and personalized content generation.

Your responsibility is to generate a highly polished, realistic, engaging, and deeply personalized professional summary that feels genuinely written by a human rather than generated by an AI system.

The generated summary must sound natural, emotionally intelligent, context-aware, and professionally authentic while maintaining clarity, structure, and readability.

PERSON DETAILS:
Name: {full_name}
Job Title: {job_title}
Bio: {bio}

SUMMARY DETAILS:
Tone: {tone}
Summary Length: {summary_length}

WRITING OBJECTIVES:

- Create a professional summary that feels authentic, human-written, and naturally expressive.
- The writing should reflect realistic human communication patterns instead of robotic or overly formal AI-generated language.
- Build a strong professional identity around the provided details while preserving natural flow and readability.
- Make the summary immersive, thoughtful, and personalized rather than generic or template-like.
- Highlight the individual's technical expertise, professional interests, learning mindset, adaptability, communication abilities, and career aspirations naturally within the writing.
- Expand meaningfully on the provided bio with contextual elaboration, professional depth, and realistic career-oriented interpretation.
- Include subtle storytelling elements where appropriate to make the content feel more organic and engaging.
- Ensure the writing captures professional confidence without sounding exaggerated or artificial.
- Emphasize qualities such as curiosity, growth mindset, collaboration, problem-solving ability, consistency, dedication, and technical passion whenever relevant.
- Maintain a strong balance between professionalism and human warmth.
- The summary should feel suitable for platforms such as LinkedIn, portfolios, resumes, professional introductions, internship profiles, startup applications, networking profiles, or AI/tech industry presentations.

LANGUAGE & WRITING STYLE GUIDELINES:

- Write in a polished, sophisticated, and naturally flowing human tone.
- Avoid repetitive sentence structures.
- Avoid robotic phrasing or AI-like generic wording.
- Avoid excessive buzzwords unless contextually meaningful.
- Ensure smooth transitions between ideas and paragraphs.
- Use varied sentence lengths and natural conversational rhythm.
- Make the content emotionally intelligent while remaining professional.
- Use strong but realistic vocabulary appropriate for professional communication.
- Keep the tone fully consistent throughout the summary.
- Make the content descriptive, insightful, and detailed without sounding unnecessarily verbose.
- Focus heavily on readability, authenticity, and professional credibility.
- If the tone is formal, maintain polished business-level language.
- If the tone is friendly or conversational, introduce a warmer and more approachable writing style while preserving professionalism.
- If the summary length is long, generate a detailed multi-paragraph professional narrative with rich elaboration and contextual insights.

CONTENT ENHANCEMENT REQUIREMENTS:

- Infer and naturally expand upon the person's likely strengths, ambitions, and working style based on the provided information.
- Add meaningful professional depth while staying aligned with the original details.
- Highlight technical skills, industry interests, project exposure, tools, technologies, and learning attitude whenever relevant.
- Create a sense of credibility, competence, and authenticity.
- Ensure the summary sounds believable and professionally realistic.
- Make the writing feel personalized to the individual instead of universally applicable.

OUTPUT REQUIREMENTS:

- Generate only the final professional summary.
- Do not include headings, labels, explanations, bullet points, or notes.
- The final response must be presentation-ready.
- The output must feel naturally written by a real person with professional writing expertise.
- Prioritize authenticity and human-like expression over generic AI-generated structure.

Now generate the detailed professional summary.
"""

prompt = PromptTemplate(
    input_variables=[
        "full_name",
        "job_title",
        "bio",
        "tone",
        "summary_length"
    ],
    template=template
)

# CHAIN

chain = prompt | llm | StrOutputParser()

# MAIN PROGRAM

person_details = get_person_details()

print("\n Person details saved!")

while True:
    choice = input("\nGenerate a summary? (yes/exit): ").lower()

    if choice == "exit":
        print("\n Exiting program...")
        break

    elif choice == "yes":

        summary_details = get_summary_details()

        # Merge dictionaries
        final_input = {
            **person_details,
            **summary_details
        }

        print("\n Generating summary...\n")

        result = chain.invoke(final_input)

        print("GENERATED SUMMARY")
        print(result)

    else:
        print(" Invalid input! Type 'yes' or 'exit'.")